{% set name = "napari-vodex" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-vodex-{{ version }}.tar.gz
  sha256: 6b5f78711c5b9487d804c26cfc451f3fd34b2ef00489fc1bc68c7d39c4e66426

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - vodex >=1.0.7

test:
  imports:
    - napari_vodex
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/LemonJust/napari-vodex
  summary: |
    A napari plugin for VoDEx: Volumetric Data and Experiment Manager.
    Allows to load volumetric data based on experimental conditions.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - LemonJust
